### ISSUE TITLE
expression tree printer as a standalone lib?

### ISSUE THREAD

**Issue by rudifa** [grafana/cuetsy#108]
In the [Cue issue #1710](https://github.com/cue-lang/cue/issues/1710), @sdboyer wrote 

_... [expression tree printer](https://github.com/grafana/cuetsy/blob/main/expr.go). i plan to turn that into a standalone lib at some point soon ..._

How soon would that be?

In the meantime, could you explain briefly how to use funcs exposed by expr.go for this purpose?

**Comment by sdboyer** [comment]
hi! thanks for asking about this -

i actually did pull it out into a standalone library, [here](https://github.com/sdboyer/cuerious). We haven't done a decent job of documenting it, though, partly because there are still some known issues with the rendering that have just made it difficult to write clean, consistent docs. (Contributions welcome! 😉)

However, what's over there is definitely an improvement over what's here, and there's at least some more guidance on the public, callable surface.

**Comment by sdboyer** [comment]
closing this as the standalone lib does exist, despite its rough form
